// Code generated by protoc-gen-go. DO NOT EDIT.
// source: organization.proto

package github_pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Organization struct {
	Login                       string               `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Id                          int64                `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	NodeId                      string               `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	AvatarUrl                   string               `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	HtmlUrl                     string               `protobuf:"bytes,5,opt,name=html_url,json=htmlUrl,proto3" json:"html_url,omitempty"`
	Name                        string               `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Company                     string               `protobuf:"bytes,7,opt,name=company,proto3" json:"company,omitempty"`
	Blog                        string               `protobuf:"bytes,8,opt,name=blog,proto3" json:"blog,omitempty"`
	Location                    string               `protobuf:"bytes,9,opt,name=location,proto3" json:"location,omitempty"`
	Email                       string               `protobuf:"bytes,10,opt,name=email,proto3" json:"email,omitempty"`
	Description                 string               `protobuf:"bytes,11,opt,name=description,proto3" json:"description,omitempty"`
	PublicRepos                 uint32               `protobuf:"varint,12,opt,name=public_repos,json=publicRepos,proto3" json:"public_repos,omitempty"`
	PublicGists                 uint32               `protobuf:"varint,13,opt,name=public_gists,json=publicGists,proto3" json:"public_gists,omitempty"`
	Followers                   uint32               `protobuf:"varint,14,opt,name=followers,proto3" json:"followers,omitempty"`
	Following                   uint32               `protobuf:"varint,15,opt,name=following,proto3" json:"following,omitempty"`
	CreatedAt                   *timestamp.Timestamp `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt                   *timestamp.Timestamp `protobuf:"bytes,17,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	TotalPrivateRepos           uint32               `protobuf:"varint,18,opt,name=total_private_repos,json=totalPrivateRepos,proto3" json:"total_private_repos,omitempty"`
	OwnedPrivateRepos           uint32               `protobuf:"varint,19,opt,name=owned_private_repos,json=ownedPrivateRepos,proto3" json:"owned_private_repos,omitempty"`
	PrivateGists                uint32               `protobuf:"varint,20,opt,name=private_gists,json=privateGists,proto3" json:"private_gists,omitempty"`
	DiskUsage                   uint32               `protobuf:"varint,21,opt,name=disk_usage,json=diskUsage,proto3" json:"disk_usage,omitempty"`
	Collaborators               uint32               `protobuf:"varint,22,opt,name=collaborators,proto3" json:"collaborators,omitempty"`
	BillingEmail                string               `protobuf:"bytes,23,opt,name=billing_email,json=billingEmail,proto3" json:"billing_email,omitempty"`
	Type                        string               `protobuf:"bytes,24,opt,name=type,proto3" json:"type,omitempty"`
	Plan                        *Plan                `protobuf:"bytes,25,opt,name=plan,proto3" json:"plan,omitempty"`
	TwoFactorRequirementEnabled bool                 `protobuf:"varint,26,opt,name=two_factor_requirement_enabled,json=twoFactorRequirementEnabled,proto3" json:"two_factor_requirement_enabled,omitempty"`
	// DefaultRepoPermission can be one of: "read", "write", "admin", or "none". (Default: "read").
	// It is only used in OrganizationsService.Edit.
	DefaultRepoPermission string `protobuf:"bytes,27,opt,name=default_repo_permission,json=defaultRepoPermission,proto3" json:"default_repo_permission,omitempty"`
	// DefaultRepoSettings can be one of: "read", "write", "admin", or "none". (Default: "read").
	// It is only used in OrganizationsService.Get.
	DefaultRepoSettings string `protobuf:"bytes,28,opt,name=default_repo_settings,json=defaultRepoSettings,proto3" json:"default_repo_settings,omitempty"`
	// MembersCanCreateRepos default value is true and is only used in Organizations.Edit.
	MembersCanCreateRepos bool `protobuf:"varint,29,opt,name=members_can_create_repos,json=membersCanCreateRepos,proto3" json:"members_can_create_repos,omitempty"`
	// https://developer.github.com/changes/2019-12-03-internal-visibility-changes/#rest-v3-api
	MembersCanCreatePublicRepos   bool     `protobuf:"varint,30,opt,name=members_can_create_public_repos,json=membersCanCreatePublicRepos,proto3" json:"members_can_create_public_repos,omitempty"`
	MembersCanCreatePrivateRepos  bool     `protobuf:"varint,31,opt,name=members_can_create_private_repos,json=membersCanCreatePrivateRepos,proto3" json:"members_can_create_private_repos,omitempty"`
	MembersCanCreateInternalRepos bool     `protobuf:"varint,32,opt,name=members_can_create_internal_repos,json=membersCanCreateInternalRepos,proto3" json:"members_can_create_internal_repos,omitempty"`
	XXX_NoUnkeyedLiteral          struct{} `json:"-"`
	XXX_unrecognized              []byte   `json:"-"`
	XXX_sizecache                 int32    `json:"-"`
}

func (m *Organization) Reset()         { *m = Organization{} }
func (m *Organization) String() string { return proto.CompactTextString(m) }
func (*Organization) ProtoMessage()    {}
func (*Organization) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d10c68ef159b9ed, []int{0}
}

func (m *Organization) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Organization.Unmarshal(m, b)
}
func (m *Organization) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Organization.Marshal(b, m, deterministic)
}
func (m *Organization) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Organization.Merge(m, src)
}
func (m *Organization) XXX_Size() int {
	return xxx_messageInfo_Organization.Size(m)
}
func (m *Organization) XXX_DiscardUnknown() {
	xxx_messageInfo_Organization.DiscardUnknown(m)
}

var xxx_messageInfo_Organization proto.InternalMessageInfo

func (m *Organization) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *Organization) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Organization) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *Organization) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *Organization) GetHtmlUrl() string {
	if m != nil {
		return m.HtmlUrl
	}
	return ""
}

func (m *Organization) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Organization) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func (m *Organization) GetBlog() string {
	if m != nil {
		return m.Blog
	}
	return ""
}

func (m *Organization) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Organization) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Organization) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Organization) GetPublicRepos() uint32 {
	if m != nil {
		return m.PublicRepos
	}
	return 0
}

func (m *Organization) GetPublicGists() uint32 {
	if m != nil {
		return m.PublicGists
	}
	return 0
}

func (m *Organization) GetFollowers() uint32 {
	if m != nil {
		return m.Followers
	}
	return 0
}

func (m *Organization) GetFollowing() uint32 {
	if m != nil {
		return m.Following
	}
	return 0
}

func (m *Organization) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Organization) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Organization) GetTotalPrivateRepos() uint32 {
	if m != nil {
		return m.TotalPrivateRepos
	}
	return 0
}

func (m *Organization) GetOwnedPrivateRepos() uint32 {
	if m != nil {
		return m.OwnedPrivateRepos
	}
	return 0
}

func (m *Organization) GetPrivateGists() uint32 {
	if m != nil {
		return m.PrivateGists
	}
	return 0
}

func (m *Organization) GetDiskUsage() uint32 {
	if m != nil {
		return m.DiskUsage
	}
	return 0
}

func (m *Organization) GetCollaborators() uint32 {
	if m != nil {
		return m.Collaborators
	}
	return 0
}

func (m *Organization) GetBillingEmail() string {
	if m != nil {
		return m.BillingEmail
	}
	return ""
}

func (m *Organization) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Organization) GetPlan() *Plan {
	if m != nil {
		return m.Plan
	}
	return nil
}

func (m *Organization) GetTwoFactorRequirementEnabled() bool {
	if m != nil {
		return m.TwoFactorRequirementEnabled
	}
	return false
}

func (m *Organization) GetDefaultRepoPermission() string {
	if m != nil {
		return m.DefaultRepoPermission
	}
	return ""
}

func (m *Organization) GetDefaultRepoSettings() string {
	if m != nil {
		return m.DefaultRepoSettings
	}
	return ""
}

func (m *Organization) GetMembersCanCreateRepos() bool {
	if m != nil {
		return m.MembersCanCreateRepos
	}
	return false
}

func (m *Organization) GetMembersCanCreatePublicRepos() bool {
	if m != nil {
		return m.MembersCanCreatePublicRepos
	}
	return false
}

func (m *Organization) GetMembersCanCreatePrivateRepos() bool {
	if m != nil {
		return m.MembersCanCreatePrivateRepos
	}
	return false
}

func (m *Organization) GetMembersCanCreateInternalRepos() bool {
	if m != nil {
		return m.MembersCanCreateInternalRepos
	}
	return false
}

func init() {
	proto.RegisterType((*Organization)(nil), "github.Organization")
}

func init() { proto.RegisterFile("organization.proto", fileDescriptor_8d10c68ef159b9ed) }

var fileDescriptor_8d10c68ef159b9ed = []byte{
	// 749 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0xcf, 0x73, 0x1b, 0x35,
	0x14, 0xc7, 0xc7, 0x69, 0x9a, 0xc4, 0x2f, 0x4e, 0x21, 0x4a, 0x43, 0x54, 0x37, 0x6e, 0xb6, 0xc0,
	0xc1, 0x97, 0xec, 0x42, 0x18, 0x60, 0x18, 0x4e, 0x25, 0xb4, 0xd0, 0x19, 0x66, 0xf0, 0x2c, 0xf4,
	0xc2, 0x65, 0x47, 0xbb, 0x2b, 0x6f, 0x05, 0x5a, 0x69, 0x91, 0xb4, 0x31, 0xed, 0xdf, 0xce, 0x81,
	0xd1, 0x93, 0x1c, 0xaf, 0x43, 0x66, 0x7a, 0xf2, 0xea, 0xfb, 0xfd, 0xbc, 0x67, 0xe9, 0xfd, 0x00,
	0xa2, 0x4d, 0xc3, 0x94, 0x78, 0xcf, 0x9c, 0xd0, 0x2a, 0xed, 0x8c, 0x76, 0x9a, 0xec, 0x35, 0xc2,
	0xbd, 0xed, 0xcb, 0xe9, 0x45, 0xa3, 0x75, 0x23, 0x79, 0x86, 0x6a, 0xd9, 0x2f, 0x33, 0x27, 0x5a,
	0x6e, 0x1d, 0x6b, 0xbb, 0x00, 0x4e, 0x8f, 0x03, 0x98, 0x75, 0x92, 0xc5, 0xd8, 0x4f, 0xff, 0x1d,
	0xc3, 0xe4, 0xd7, 0x41, 0x4a, 0xf2, 0x18, 0x1e, 0x4a, 0xdd, 0x08, 0x45, 0x47, 0xc9, 0x68, 0x3e,
	0xce, 0xc3, 0x81, 0x3c, 0x82, 0x1d, 0x51, 0xd3, 0x9d, 0x64, 0x34, 0x7f, 0x90, 0xef, 0x88, 0x9a,
	0x9c, 0xc1, 0xbe, 0xd2, 0x35, 0x2f, 0x44, 0x4d, 0x1f, 0x20, 0xb7, 0xe7, 0x8f, 0xaf, 0x6b, 0x32,
	0x03, 0x60, 0x37, 0xcc, 0x31, 0x53, 0xf4, 0x46, 0xd2, 0x5d, 0xf4, 0xc6, 0x41, 0x79, 0x63, 0x24,
	0x79, 0x02, 0x07, 0x6f, 0x5d, 0x2b, 0xd1, 0x7c, 0x88, 0xe6, 0xbe, 0x3f, 0x7b, 0x8b, 0xc0, 0xae,
	0x62, 0x2d, 0xa7, 0x7b, 0x28, 0xe3, 0x37, 0xa1, 0xb0, 0x5f, 0xe9, 0xb6, 0x63, 0xea, 0x1d, 0xdd,
	0x0f, 0x74, 0x3c, 0x7a, 0xba, 0x94, 0xba, 0xa1, 0x07, 0x81, 0xf6, 0xdf, 0x64, 0x0a, 0x07, 0x52,
	0x57, 0xf8, 0x0c, 0x3a, 0x46, 0xfd, 0xf6, 0xec, 0x9f, 0xc5, 0x5b, 0x26, 0x24, 0x85, 0xf0, 0x2c,
	0x3c, 0x90, 0x04, 0x0e, 0x6b, 0x6e, 0x2b, 0x23, 0x3a, 0x0c, 0x3a, 0x44, 0x6f, 0x28, 0x91, 0xe7,
	0x30, 0xe9, 0xfa, 0x52, 0x8a, 0xaa, 0x30, 0xbc, 0xd3, 0x96, 0x4e, 0x92, 0xd1, 0xfc, 0x28, 0x3f,
	0x0c, 0x5a, 0xee, 0xa5, 0x01, 0xd2, 0x08, 0xeb, 0x2c, 0x3d, 0x1a, 0x22, 0x3f, 0x79, 0x89, 0x9c,
	0xc3, 0x78, 0xa9, 0xa5, 0xd4, 0x2b, 0x6e, 0x2c, 0x7d, 0x84, 0xfe, 0x46, 0xd8, 0xb8, 0x42, 0x35,
	0xf4, 0xa3, 0xa1, 0x2b, 0x54, 0x43, 0xbe, 0x03, 0xa8, 0x0c, 0x67, 0x8e, 0xd7, 0x05, 0x73, 0xf4,
	0xe3, 0x64, 0x34, 0x3f, 0xbc, 0x9a, 0xa6, 0xa1, 0xd5, 0xe9, 0xba, 0xd5, 0xe9, 0xef, 0xeb, 0x56,
	0xe7, 0xe3, 0x48, 0xbf, 0x70, 0x3e, 0xb4, 0xef, 0xea, 0x75, 0xe8, 0xf1, 0x87, 0x43, 0x23, 0xfd,
	0xc2, 0x91, 0x14, 0x4e, 0x9c, 0x76, 0x4c, 0x16, 0x9d, 0x11, 0x37, 0xcc, 0xf1, 0xf8, 0x7c, 0x82,
	0xb7, 0x3b, 0x46, 0x6b, 0x11, 0x9c, 0x50, 0x84, 0x14, 0x4e, 0xf4, 0x4a, 0xf1, 0xfa, 0x0e, 0x7f,
	0x12, 0x78, 0xb4, 0xb6, 0xf8, 0xcf, 0xe0, 0x68, 0x4d, 0x86, 0xaa, 0x3d, 0x46, 0x72, 0x12, 0xc5,
	0x50, 0xb6, 0x19, 0x40, 0x2d, 0xec, 0x5f, 0x45, 0x6f, 0x59, 0xc3, 0xe9, 0x69, 0xa8, 0x8c, 0x57,
	0xde, 0x78, 0x81, 0x7c, 0x0e, 0x47, 0x95, 0x96, 0x92, 0x95, 0xda, 0x30, 0xa7, 0x8d, 0xa5, 0x9f,
	0x20, 0xb1, 0x2d, 0xfa, 0x7f, 0x2a, 0x85, 0x94, 0x42, 0x35, 0x45, 0x98, 0x80, 0x33, 0xec, 0xf2,
	0x24, 0x8a, 0x2f, 0x71, 0x10, 0x08, 0xec, 0xba, 0x77, 0x1d, 0xa7, 0x34, 0x8c, 0x93, 0xff, 0x26,
	0x09, 0xec, 0xfa, 0x45, 0xa1, 0x4f, 0xb0, 0x6e, 0x93, 0x34, 0x2c, 0x4f, 0xba, 0x90, 0x4c, 0xe5,
	0xe8, 0x90, 0x6b, 0x78, 0xe6, 0x56, 0xba, 0x58, 0xb2, 0xca, 0x69, 0x53, 0x18, 0xfe, 0x77, 0x2f,
	0x0c, 0x6f, 0xb9, 0x72, 0x05, 0x57, 0xac, 0x94, 0xbc, 0xa6, 0xd3, 0x64, 0x34, 0x3f, 0xc8, 0x9f,
	0xba, 0x95, 0x7e, 0x85, 0x50, 0xbe, 0x61, 0x5e, 0x06, 0x84, 0x7c, 0x03, 0x67, 0x35, 0x5f, 0xb2,
	0x5e, 0x3a, 0xac, 0x59, 0xd1, 0x71, 0xd3, 0x0a, 0x6b, 0xfd, 0x3c, 0x3e, 0xc5, 0xdb, 0x9c, 0x46,
	0xdb, 0x17, 0x6e, 0x71, 0x6b, 0x92, 0x2b, 0x38, 0xdd, 0x8a, 0xb3, 0xdc, 0x39, 0xa1, 0x1a, 0x4b,
	0xcf, 0x31, 0xea, 0x64, 0x10, 0xf5, 0x5b, 0xb4, 0xc8, 0xb7, 0x40, 0x5b, 0xde, 0x96, 0xdc, 0xd8,
	0xa2, 0x62, 0xaa, 0x08, 0x93, 0x12, 0x5b, 0x35, 0xc3, 0xab, 0x9e, 0x46, 0xff, 0x9a, 0xa9, 0x6b,
	0x74, 0x43, 0xbb, 0x7e, 0x84, 0x8b, 0x7b, 0x02, 0xb7, 0x36, 0xe3, 0x59, 0x78, 0xea, 0xdd, 0xf8,
	0xc5, 0x60, 0x53, 0x5e, 0x41, 0x72, 0x5f, 0x96, 0xad, 0x89, 0xb9, 0xc0, 0x34, 0xe7, 0xff, 0x4b,
	0x33, 0x1c, 0x9e, 0x9f, 0xe1, 0xf9, 0x3d, 0x79, 0x84, 0x72, 0xdc, 0x28, 0x26, 0x63, 0xa2, 0x04,
	0x13, 0xcd, 0xee, 0x26, 0x7a, 0x1d, 0x29, 0xcc, 0xf4, 0x83, 0x86, 0x59, 0xcd, 0x6f, 0x52, 0xf1,
	0xbe, 0x6f, 0x85, 0xfa, 0xfa, 0xea, 0xcb, 0x2f, 0x52, 0xcb, 0x54, 0x5d, 0xea, 0x7f, 0x62, 0xb7,
	0x17, 0xa3, 0x3f, 0x7e, 0x89, 0x7d, 0xaf, 0x74, 0x9b, 0x6d, 0xb8, 0xcb, 0xc8, 0x65, 0x86, 0xff,
	0xa9, 0x85, 0xe2, 0xe6, 0x92, 0x75, 0x7e, 0x65, 0x2f, 0x2d, 0x6b, 0x3b, 0xc9, 0x33, 0xd6, 0x89,
	0xac, 0xd1, 0x59, 0x88, 0xfd, 0x3e, 0xfc, 0x14, 0x5d, 0x59, 0xee, 0xe1, 0xda, 0x7d, 0xf5, 0x5f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xeb, 0xa0, 0x50, 0xff, 0xc8, 0x05, 0x00, 0x00,
}
