// Code generated by protoc-gen-go. DO NOT EDIT.
// source: item.proto

package qiita_pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListItemsRequest struct {
	// Required. User ID.
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListItemsRequest) Reset()         { *m = ListItemsRequest{} }
func (m *ListItemsRequest) String() string { return proto.CompactTextString(m) }
func (*ListItemsRequest) ProtoMessage()    {}
func (*ListItemsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{0}
}

func (m *ListItemsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListItemsRequest.Unmarshal(m, b)
}
func (m *ListItemsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListItemsRequest.Marshal(b, m, deterministic)
}
func (m *ListItemsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListItemsRequest.Merge(m, src)
}
func (m *ListItemsRequest) XXX_Size() int {
	return xxx_messageInfo_ListItemsRequest.Size(m)
}
func (m *ListItemsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListItemsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListItemsRequest proto.InternalMessageInfo

func (m *ListItemsRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type ListItemsResponse struct {
	Items                []*Item  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListItemsResponse) Reset()         { *m = ListItemsResponse{} }
func (m *ListItemsResponse) String() string { return proto.CompactTextString(m) }
func (*ListItemsResponse) ProtoMessage()    {}
func (*ListItemsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{1}
}

func (m *ListItemsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListItemsResponse.Unmarshal(m, b)
}
func (m *ListItemsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListItemsResponse.Marshal(b, m, deterministic)
}
func (m *ListItemsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListItemsResponse.Merge(m, src)
}
func (m *ListItemsResponse) XXX_Size() int {
	return xxx_messageInfo_ListItemsResponse.Size(m)
}
func (m *ListItemsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListItemsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListItemsResponse proto.InternalMessageInfo

func (m *ListItemsResponse) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type Item struct {
	// Required. Item body in HTML.
	RenderedBody string `protobuf:"bytes,1,opt,name=rendered_body,json=renderedBody,proto3" json:"rendered_body,omitempty"`
	// Required. Item body in Markdown.
	Body string `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	// Required. A flag whether this item is co-edit mode (only available on Qiita Team).
	Coediting bool `protobuf:"varint,3,opt,name=coediting,proto3" json:"coediting,omitempty"`
	// Required. Comments count.
	CommentsCount uint32 `protobuf:"varint,4,opt,name=comments_count,json=commentsCount,proto3" json:"comments_count,omitempty"`
	// Required. Date-time when this data was created.
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Required. Represents a group on Qiita Team.
	Group string `protobuf:"bytes,6,opt,name=group,proto3" json:"group,omitempty"`
	// Required. An unique item ID
	Id string `protobuf:"bytes,7,opt,name=id,proto3" json:"id,omitempty"`
	// Required. Likes count (only available on Qiita).
	LikesCount uint32 `protobuf:"varint,8,opt,name=likes_count,json=likesCount,proto3" json:"likes_count,omitempty"`
	// Required. A flag whether this item is private (only available on Qiita).
	Private bool `protobuf:"varint,9,opt,name=private,proto3" json:"private,omitempty"`
	// Required. Emoji reactions count (only availabble on Qiita Team).
	ReactionsCount uint32 `protobuf:"varint,10,opt,name=reactions_count,json=reactionsCount,proto3" json:"reactions_count,omitempty"`
	// Required. A list of tags.
	Tags []*Item_Tag `protobuf:"bytes,11,rep,name=tags,proto3" json:"tags,omitempty"`
	// Required. The title of this item.
	Title string `protobuf:"bytes,12,opt,name=title,proto3" json:"title,omitempty"`
	// Required. Date-time when this data was updated.
	UpdatedAt *timestamp.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Required. The URL of this item.
	Url string `protobuf:"bytes,14,opt,name=url,proto3" json:"url,omitempty"`
	// Required. A Qiita user (a.k.a. account)
	User *User `protobuf:"bytes,15,opt,name=user,proto3" json:"user,omitempty"`
	// Optional.  The number of views.
	PageViewsCount       uint32   `protobuf:"varint,16,opt,name=page_views_count,json=pageViewsCount,proto3" json:"page_views_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{2}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetRenderedBody() string {
	if m != nil {
		return m.RenderedBody
	}
	return ""
}

func (m *Item) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Item) GetCoediting() bool {
	if m != nil {
		return m.Coediting
	}
	return false
}

func (m *Item) GetCommentsCount() uint32 {
	if m != nil {
		return m.CommentsCount
	}
	return 0
}

func (m *Item) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Item) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *Item) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Item) GetLikesCount() uint32 {
	if m != nil {
		return m.LikesCount
	}
	return 0
}

func (m *Item) GetPrivate() bool {
	if m != nil {
		return m.Private
	}
	return false
}

func (m *Item) GetReactionsCount() uint32 {
	if m != nil {
		return m.ReactionsCount
	}
	return 0
}

func (m *Item) GetTags() []*Item_Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Item) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Item) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Item) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Item) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Item) GetPageViewsCount() uint32 {
	if m != nil {
		return m.PageViewsCount
	}
	return 0
}

type Item_Tag struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Versions             []string `protobuf:"bytes,2,rep,name=versions,proto3" json:"versions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item_Tag) Reset()         { *m = Item_Tag{} }
func (m *Item_Tag) String() string { return proto.CompactTextString(m) }
func (*Item_Tag) ProtoMessage()    {}
func (*Item_Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{2, 0}
}

func (m *Item_Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item_Tag.Unmarshal(m, b)
}
func (m *Item_Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item_Tag.Marshal(b, m, deterministic)
}
func (m *Item_Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item_Tag.Merge(m, src)
}
func (m *Item_Tag) XXX_Size() int {
	return xxx_messageInfo_Item_Tag.Size(m)
}
func (m *Item_Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Item_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Item_Tag proto.InternalMessageInfo

func (m *Item_Tag) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Item_Tag) GetVersions() []string {
	if m != nil {
		return m.Versions
	}
	return nil
}

type ListStocksRequest struct {
	// Required. User ID.
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListStocksRequest) Reset()         { *m = ListStocksRequest{} }
func (m *ListStocksRequest) String() string { return proto.CompactTextString(m) }
func (*ListStocksRequest) ProtoMessage()    {}
func (*ListStocksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{3}
}

func (m *ListStocksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListStocksRequest.Unmarshal(m, b)
}
func (m *ListStocksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListStocksRequest.Marshal(b, m, deterministic)
}
func (m *ListStocksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListStocksRequest.Merge(m, src)
}
func (m *ListStocksRequest) XXX_Size() int {
	return xxx_messageInfo_ListStocksRequest.Size(m)
}
func (m *ListStocksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListStocksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListStocksRequest proto.InternalMessageInfo

func (m *ListStocksRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type ListStocksResponse struct {
	Items                []*Item  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListStocksResponse) Reset()         { *m = ListStocksResponse{} }
func (m *ListStocksResponse) String() string { return proto.CompactTextString(m) }
func (*ListStocksResponse) ProtoMessage()    {}
func (*ListStocksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{4}
}

func (m *ListStocksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListStocksResponse.Unmarshal(m, b)
}
func (m *ListStocksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListStocksResponse.Marshal(b, m, deterministic)
}
func (m *ListStocksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListStocksResponse.Merge(m, src)
}
func (m *ListStocksResponse) XXX_Size() int {
	return xxx_messageInfo_ListStocksResponse.Size(m)
}
func (m *ListStocksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListStocksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListStocksResponse proto.InternalMessageInfo

func (m *ListStocksResponse) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*ListItemsRequest)(nil), "qiita.ListItemsRequest")
	proto.RegisterType((*ListItemsResponse)(nil), "qiita.ListItemsResponse")
	proto.RegisterType((*Item)(nil), "qiita.Item")
	proto.RegisterType((*Item_Tag)(nil), "qiita.Item.Tag")
	proto.RegisterType((*ListStocksRequest)(nil), "qiita.ListStocksRequest")
	proto.RegisterType((*ListStocksResponse)(nil), "qiita.ListStocksResponse")
}

func init() { proto.RegisterFile("item.proto", fileDescriptor_6007f868cf6553df) }

var fileDescriptor_6007f868cf6553df = []byte{
	// 606 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x5f, 0x6f, 0xd3, 0x3e,
	0x14, 0xfd, 0xa5, 0x7f, 0xb6, 0xf5, 0x76, 0xed, 0xfa, 0xb3, 0x90, 0x66, 0xaa, 0x49, 0x2b, 0x9d,
	0x10, 0x91, 0x60, 0x09, 0x14, 0x0d, 0x84, 0x78, 0x61, 0xdb, 0xd3, 0x24, 0x1e, 0x50, 0x36, 0x78,
	0xe0, 0xa5, 0x72, 0xe3, 0x4b, 0x64, 0x96, 0xc4, 0x99, 0xed, 0x14, 0xc6, 0xe7, 0xe0, 0x9b, 0xf1,
	0x85, 0x90, 0xed, 0x66, 0x2b, 0x7f, 0xa4, 0xf1, 0x12, 0xf9, 0x9e, 0x7b, 0xee, 0xcd, 0x39, 0xd7,
	0xd7, 0x00, 0xc2, 0x60, 0x11, 0x55, 0x4a, 0x1a, 0x49, 0xba, 0x57, 0x42, 0x18, 0x36, 0xde, 0xcf,
	0xa4, 0xcc, 0x72, 0x8c, 0x1d, 0xb8, 0xa8, 0x3f, 0xc5, 0x46, 0x14, 0xa8, 0x0d, 0x2b, 0x2a, 0xcf,
	0x1b, 0x8f, 0x1c, 0x2f, 0xae, 0x35, 0x2a, 0x8f, 0x4c, 0x1f, 0xc3, 0xe8, 0xad, 0xd0, 0xe6, 0xcc,
	0x60, 0xa1, 0x13, 0xbc, 0xaa, 0x51, 0x1b, 0xb2, 0x0b, 0x9b, 0x96, 0x31, 0x17, 0x9c, 0x06, 0x93,
	0x20, 0xec, 0x25, 0x1b, 0x36, 0x3c, 0xe3, 0xd3, 0x17, 0xf0, 0xff, 0x1a, 0x59, 0x57, 0xb2, 0xd4,
	0x48, 0x1e, 0x40, 0xd7, 0x2a, 0xd1, 0x34, 0x98, 0xb4, 0xc3, 0xfe, 0xac, 0x1f, 0xb9, 0x7f, 0x44,
	0x96, 0x94, 0xf8, 0xcc, 0xf4, 0x47, 0x07, 0x3a, 0x36, 0x26, 0x07, 0x30, 0x50, 0x58, 0x72, 0x54,
	0xc8, 0xe7, 0x0b, 0xc9, 0xaf, 0x57, 0xfd, 0xb7, 0x1b, 0xf0, 0x44, 0xf2, 0x6b, 0x42, 0xa0, 0xe3,
	0x72, 0x2d, 0x97, 0x73, 0x67, 0xb2, 0x07, 0xbd, 0x54, 0x22, 0x17, 0x46, 0x94, 0x19, 0x6d, 0x4f,
	0x82, 0x70, 0x2b, 0xb9, 0x05, 0xc8, 0x43, 0x18, 0xa6, 0xb2, 0x28, 0xb0, 0x34, 0x7a, 0x9e, 0xca,
	0xba, 0x34, 0xb4, 0x33, 0x09, 0xc2, 0x41, 0x32, 0x68, 0xd0, 0x53, 0x0b, 0x92, 0x57, 0x00, 0xa9,
	0x42, 0x66, 0x90, 0xcf, 0x99, 0xa1, 0xdd, 0x49, 0x10, 0xf6, 0x67, 0xe3, 0xc8, 0xcf, 0x2c, 0x6a,
	0x66, 0x16, 0x5d, 0x34, 0x33, 0x4b, 0x7a, 0x2b, 0xf6, 0xb1, 0x21, 0xf7, 0xa0, 0x9b, 0x29, 0x59,
	0x57, 0x74, 0xc3, 0x89, 0xf2, 0x01, 0x19, 0x42, 0x4b, 0x70, 0xba, 0xe9, 0xa0, 0x96, 0xe0, 0x64,
	0x1f, 0xfa, 0xb9, 0xb8, 0xc4, 0x46, 0xc4, 0x96, 0x13, 0x01, 0x0e, 0xf2, 0x0a, 0x28, 0x6c, 0x56,
	0x4a, 0x2c, 0x99, 0x41, 0xda, 0x73, 0x26, 0x9a, 0x90, 0x3c, 0x82, 0x1d, 0x85, 0x2c, 0x35, 0x42,
	0x96, 0x4d, 0x39, 0xb8, 0xf2, 0xe1, 0x0d, 0xec, 0x5b, 0x1c, 0x40, 0xc7, 0xb0, 0x4c, 0xd3, 0xbe,
	0x9b, 0xf6, 0xce, 0xda, 0xb4, 0xa3, 0x0b, 0x96, 0x25, 0x2e, 0x69, 0xe5, 0x1a, 0x61, 0x72, 0xa4,
	0xdb, 0x5e, 0xae, 0x0b, 0xac, 0xff, 0xba, 0xe2, 0x8d, 0xff, 0xc1, 0xdd, 0xfe, 0x57, 0xec, 0x63,
	0x43, 0x46, 0xd0, 0xae, 0x55, 0x4e, 0x87, 0xae, 0x9d, 0x3d, 0x92, 0x7d, 0xe8, 0xd8, 0xad, 0xa0,
	0x3b, 0xae, 0x4d, 0x73, 0xeb, 0xef, 0x35, 0xaa, 0xc4, 0x25, 0x48, 0x08, 0xa3, 0x8a, 0x65, 0x38,
	0x5f, 0x0a, 0xfc, 0xd2, 0x58, 0x1a, 0x79, 0x4b, 0x16, 0xff, 0x60, 0x61, 0x67, 0x69, 0x7c, 0x04,
	0xed, 0x0b, 0x96, 0xd9, 0x7b, 0x2f, 0x59, 0x81, 0xab, 0x9d, 0x70, 0x67, 0x32, 0x86, 0xad, 0x25,
	0x2a, 0x6d, 0xed, 0xd3, 0xd6, 0xa4, 0x1d, 0xf6, 0x92, 0x9b, 0x78, 0xfa, 0xc4, 0x6f, 0xe3, 0xb9,
	0x91, 0xe9, 0xe5, 0xdd, 0xbb, 0xfb, 0x12, 0xc8, 0x3a, 0xfb, 0x9f, 0x97, 0x77, 0xf6, 0x3d, 0x80,
	0xbe, 0x8d, 0xcf, 0x51, 0x2d, 0x45, 0x8a, 0xe4, 0x0d, 0xf4, 0x6e, 0x1e, 0x01, 0xd9, 0x5d, 0x15,
	0xfc, 0xfe, 0x86, 0xc6, 0xf4, 0xcf, 0x84, 0xff, 0xe5, 0xf4, 0x3f, 0x72, 0x0a, 0x70, 0x2b, 0x85,
	0xac, 0x33, 0x7f, 0xf1, 0x32, 0xbe, 0xff, 0x97, 0x4c, 0xd3, 0xe4, 0xe4, 0x12, 0xf6, 0x38, 0x2e,
	0x23, 0xf1, 0xad, 0x2e, 0x44, 0x79, 0x34, 0x7b, 0xf6, 0x34, 0xd2, 0xac, 0xe4, 0x0b, 0xf9, 0xd5,
	0x17, 0xbd, 0x0b, 0x3e, 0x9e, 0xf9, 0xea, 0x54, 0x16, 0xf1, 0x2d, 0xeb, 0x70, 0xc5, 0x8a, 0x15,
	0x7e, 0x96, 0xa2, 0x44, 0x75, 0xc8, 0x2a, 0x99, 0xe7, 0xf2, 0x50, 0xb3, 0xa2, 0xca, 0x31, 0x66,
	0x95, 0x88, 0x33, 0x19, 0xbb, 0xd2, 0xd7, 0xee, 0x3b, 0xaf, 0x16, 0x8b, 0x0d, 0xb7, 0x1d, 0xcf,
	0x7f, 0x06, 0x00, 0x00, 0xff, 0xff, 0x26, 0x69, 0x6e, 0x3d, 0x74, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ItemServiceClient is the client API for ItemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ItemServiceClient interface {
	ListItems(ctx context.Context, in *ListItemsRequest, opts ...grpc.CallOption) (*ListItemsResponse, error)
	ListStocks(ctx context.Context, in *ListStocksRequest, opts ...grpc.CallOption) (*ListStocksResponse, error)
}

type itemServiceClient struct {
	cc *grpc.ClientConn
}

func NewItemServiceClient(cc *grpc.ClientConn) ItemServiceClient {
	return &itemServiceClient{cc}
}

func (c *itemServiceClient) ListItems(ctx context.Context, in *ListItemsRequest, opts ...grpc.CallOption) (*ListItemsResponse, error) {
	out := new(ListItemsResponse)
	err := c.cc.Invoke(ctx, "/qiita.ItemService/ListItems", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) ListStocks(ctx context.Context, in *ListStocksRequest, opts ...grpc.CallOption) (*ListStocksResponse, error) {
	out := new(ListStocksResponse)
	err := c.cc.Invoke(ctx, "/qiita.ItemService/ListStocks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ItemServiceServer is the server API for ItemService service.
type ItemServiceServer interface {
	ListItems(context.Context, *ListItemsRequest) (*ListItemsResponse, error)
	ListStocks(context.Context, *ListStocksRequest) (*ListStocksResponse, error)
}

// UnimplementedItemServiceServer can be embedded to have forward compatible implementations.
type UnimplementedItemServiceServer struct {
}

func (*UnimplementedItemServiceServer) ListItems(ctx context.Context, req *ListItemsRequest) (*ListItemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListItems not implemented")
}
func (*UnimplementedItemServiceServer) ListStocks(ctx context.Context, req *ListStocksRequest) (*ListStocksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListStocks not implemented")
}

func RegisterItemServiceServer(s *grpc.Server, srv ItemServiceServer) {
	s.RegisterService(&_ItemService_serviceDesc, srv)
}

func _ItemService_ListItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).ListItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qiita.ItemService/ListItems",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).ListItems(ctx, req.(*ListItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_ListStocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).ListStocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qiita.ItemService/ListStocks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).ListStocks(ctx, req.(*ListStocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ItemService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "qiita.ItemService",
	HandlerType: (*ItemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListItems",
			Handler:    _ItemService_ListItems_Handler,
		},
		{
			MethodName: "ListStocks",
			Handler:    _ItemService_ListStocks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "item.proto",
}
