load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "user_proto",
    srcs = ["user.proto"],
    deps = [],
    visibility = ["//visibility:public"],
)

proto_library(
    name = "item_proto",
    srcs = ["item.proto"],
    deps = [],
    visibility = ["//visibility:public"],
)
