# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qiita/item.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'qiita/user_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("qiita/item.proto", :syntax => :proto3) do
    add_message "qiita.ListItemsRequest" do
      optional :user_id, :string, 1
    end
    add_message "qiita.ListItemsResponse" do
      repeated :items, :message, 1, "qiita.Item"
    end
    add_message "qiita.Item" do
      optional :rendered_body, :string, 1
      optional :body, :string, 2
      optional :coediting, :bool, 3
      optional :comments_count, :uint32, 4
      optional :created_at, :message, 5, "google.protobuf.Timestamp"
      optional :group, :string, 6
      optional :id, :string, 7
      optional :likes_count, :uint32, 8
      optional :private, :bool, 9
      optional :reactions_count, :uint32, 10
      repeated :tags, :message, 11, "qiita.Item.Tag"
      optional :title, :string, 12
      optional :updated_at, :message, 13, "google.protobuf.Timestamp"
      optional :url, :string, 14
      optional :user, :message, 15, "qiita.User"
      optional :page_views_count, :uint32, 16
    end
    add_message "qiita.Item.Tag" do
      optional :name, :string, 1
      repeated :versions, :string, 2
    end
    add_message "qiita.ListStocksRequest" do
      optional :user_id, :string, 1
    end
    add_message "qiita.ListStocksResponse" do
      repeated :items, :message, 1, "qiita.Item"
    end
  end
end

module QiitaPb
  ListItemsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("qiita.ListItemsRequest").msgclass
  ListItemsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("qiita.ListItemsResponse").msgclass
  Item = Google::Protobuf::DescriptorPool.generated_pool.lookup("qiita.Item").msgclass
  Item::Tag = Google::Protobuf::DescriptorPool.generated_pool.lookup("qiita.Item.Tag").msgclass
  ListStocksRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("qiita.ListStocksRequest").msgclass
  ListStocksResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("qiita.ListStocksResponse").msgclass
end
