# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qiita/user.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("qiita/user.proto", :syntax => :proto3) do
    add_message "qiita.GetUserRequest" do
      optional :user_id, :string, 1
    end
    add_message "qiita.User" do
      optional :description, :string, 1
      optional :facebook_id, :string, 2
      optional :followees_count, :uint32, 3
      optional :followers_count, :uint32, 4
      optional :github_login_name, :string, 5
      optional :id, :string, 6
      optional :items_count, :uint32, 7
      optional :linkedin_id, :string, 8
      optional :location, :string, 9
      optional :name, :string, 10
      optional :organization, :string, 11
      optional :permanent_id, :uint32, 12
      optional :profile_image_url, :string, 13
      optional :team_only, :bool, 14
      optional :twitter_screen_name, :string, 15
      optional :website_url, :string, 16
    end
  end
end

module QiitaPb
  GetUserRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("qiita.GetUserRequest").msgclass
  User = Google::Protobuf::DescriptorPool.generated_pool.lookup("qiita.User").msgclass
end
